RealEstateAgency4/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using RealEstateAgency4.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace RealEstateAgency4.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

RealEstateAgency4/Controllers/SellersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using RealEstateAgency4.Filters;
using RealEstateAgency4.Middleware;
using RealEstateAgency4.Models;
using RealEstateAgency4.Services;
using RealEstateAgency4.ViewModels;

namespace RealEstateAgency4.Controllers
{
    [Authorize]
    public class SellersController : Controller
    {
        private readonly RealEstateAgencyContext _context;

        private readonly int pageSize = 12;
        public SellersController(RealEstateAgencyContext context)
        {
            _context = context;
        }

        // GET: Sellers
        public async Task<IActionResult> Index(SortState sortOrder, int page = 1)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<SellersCache>();

            SellersViewModel sellersViewModel;

            var sellers = HttpContext.Session.Get<SellersViewModel>("Seller");

            if (sellers == null)
            {
                sellers = new SellersViewModel();
            }

            IEnumerable<Seller> sellerContext = cache.GetSellers();

            sellerContext = Sort_Search(sellerContext, sortOrder, sellers.DateOfBirth, sellers.FullName ?? "", sellers.Gender ?? "", sellers.Address ?? "", sellers.Phone ?? "", sellers.PassportDate ?? "", sellers.ApartmentAddress ?? "", sellers.Price,
            sellers.AdditionalInformation ?? "", sellers.ApartmentName ?? "");

            // Разбиение на страницы
            var count = sellerContext.Count();
            sellerContext = sellerContext.Skip((page - 1) * pageSize).Take(pageSize);

            // Формирование модели для передачи представлению
            SellersViewModel sellerModel = new SellersViewModel
            {
                sellers = sellerContext,
                pageViewModel = new PageViewModel(count, page, pageSize),
                sortViewModel = new SortViewModel(sortOrder),
                DateOfBirth = sellers.DateOfBirth,
                FullName = sellers.FullName,
                Gender = sellers.Gender,
                Address = sellers.Address,
                Phone = sellers.Phone,
                PassportDate = sellers.PassportDate,
                ApartmentAddress = sellers.ApartmentAddress,
                Price = sellers.Price,
                AdditionalInformation = sellers.AdditionalInformation,
                ApartmentName = sellers.ApartmentName,
            };
            return View(sellerModel);

        }

        [HttpPost]
        public async Task<IActionResult> Index(SellersViewModel seller)
        {
            HttpContext.Session.Set("Seller", seller);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<SellersCache>();
            if (id == null || _context.Sellers == null)
            {
                return NotFound();
            }

            var seller = cache.GetSellers()
                .FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "Name");
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Seller seller)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<SellersCache>();

            if (ModelState.IsValid)
            {
                _context.Add(seller);
                await _context.SaveChangesAsync();
                cache.SetSellers();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "Name", seller.ApartmentId);
            return View(seller);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<SellersCache>();

            if (id == null || _context.Sellers == null)
            {
                return NotFound();
            }

            var seller = cache.GetSellers().FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }
            ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "Name", seller.ApartmentId);
            return View(seller);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, Seller seller)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<SellersCache>();

            if (id != seller.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(seller);
                    cache.SetSellers();
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SellerExists(seller.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "Name", seller.ApartmentId);
            return View(seller);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<SellersCache>();

            if (id == null || _context.Sellers == null)
            {
                return NotFound();
            }

            var seller = cache.GetSellers()
                .FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<SellersCache>();

            if (_context.Sellers == null)
            {
                return Problem("Entity set 'RealEstateAgencyContext.Sellers'  is null.");
            }

            var seller = cache.GetSellers()
                .FirstOrDefault(m => m.Id == id);
            if (seller != null)
            {
                _context.Sellers.Remove(seller);
            }

            await _context.SaveChangesAsync();
            cache.SetSellers();
            return RedirectToAction(nameof(Index));
        }

        private bool SellerExists(int id)
        {
            return (_context.Sellers?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private IEnumerable<Seller> Sort_Search(IEnumerable<Seller> sellers, SortState sortOrder, DateTime? searchDateOfBirth, string searchFullName,
            string searchGender, string searchAddress, string searchPhone, string searchPassportDate, string searchApartmentAddress, decimal SellerPrice, string AdditionalInformation, string ApartmentName)
        {
            switch (sortOrder)
            {
                case SortState.DateOfBirthAsc:
                    sellers = sellers.OrderBy(s => s.DateOfBirth);
                    break;
                case SortState.DateOfBirthDesc:
                    sellers = sellers.OrderByDescending(s => s.DateOfBirth);
                    break;
                case SortState.PriceSellerAsc:
                    sellers = sellers.OrderBy(s => s.Price);
                    break;
                case SortState.PriceSellerDesc:
                    sellers = sellers.OrderByDescending(s => s.Price);
                    break;


            }
            sellers = sellers
        .Where(c =>
            (c.DateOfBirth == searchDateOfBirth || searchDateOfBirth == DateTime.MinValue || searchDateOfBirth == null)
            && (c.FullName == searchFullName || searchFullName.IsNullOrEmpty())
            && (c.Gender.Contains(searchGender ?? ""))
            && (c.Address.Contains(searchAddress ?? ""))
            && (c.Phone.Contains(searchPhone ?? ""))
            && (c.PassportData.Contains(searchPassportDate ?? ""))
            && (c.Apartment.Name == ApartmentName || ApartmentName.IsNullOrEmpty())
            && (c.ApartmentAddress == searchApartmentAddress || searchApartmentAddress.IsNullOrEmpty())
            && (c.Price == SellerPrice || SellerPrice == 0)
            && (c.AdditionalInformation == AdditionalInformation || AdditionalInformation.IsNullOrEmpty())
        );
            return sellers;
        }
    }
}

RealEstateAgency4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RealEstateAgency</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RealEstateAgency4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-emoji-smile" viewBox="0 0 16 16" style="margin-right: 8px;">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
                    <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5m4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5" />
                </svg>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Риелтерское агентство</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная страница</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contracts" asp-action="Index">Договора</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apartments" asp-action="Index">Квартиры</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sellers" asp-action="Index">Продавцы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Услуги</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RealEstateAgency4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>