RealEstateAgency4/Models/Contract.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RealEstateAgency4.Models;

public partial class Contract
{
    public int Id { get; set; }

    [DataType(DataType.Date)]
    [Display(Name = "Дата")]
    public DateTime DateOfContract { get; set; }

    [Display(Name = "Продавец")]
    public int SellerId { get; set; }

    [Display(Name = "Сумма сделки")]
    public decimal DealAmount { get; set; }
    [Display(Name = "Стоимость услуги")]
    public decimal ServiceCost { get; set; }
    [Display(Name = "Сотрудник")]
    public string Employee { get; set; }
    [Display(Name = "Покупатель")]
    public string Fiobuyer { get; set; }


    public virtual ICollection<ContractService> ContractServices { get; set; } = new List<ContractService>();

    public virtual Seller? Seller { get; set; }
}

RealEstateAgency4/ViewModels/ContractsViewModel.cs
using RealEstateAgency4.Models;
using System.ComponentModel.DataAnnotations;
using static RealEstateAgency4.ViewModels.SortViewModel;

namespace RealEstateAgency4.ViewModels
{

    public class ContractsViewModel
    {
        public IEnumerable<Contract> contracts { get; set; }
        public PageViewModel pageViewModel { get; set; } 
        public SortViewModel sortViewModel { get; set; }
        [Display(Name = "Дата заключения")]
        public DateTime? DateOfContract { get; set; }

        [Display(Name = "Продавец")]
        public string SellerName { get; set; }
        [Display(Name = "Цена сделки")]
        public decimal DealAmount { get; set; }
        [Display(Name = "Стоимость услуг")]
        public decimal ServiceCost { get; set; }
        [Display(Name = "Сотрудник")]
        public string Employee { get; set; }
        [Display(Name = "Покупатель")]
        public string Fiobuyer { get; set; }
    }
}

RealEstateAgency4/Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using RealEstateAgency4.Filters;
using RealEstateAgency4.Middleware;
using RealEstateAgency4.Models;
using RealEstateAgency4.Services;
using RealEstateAgency4.ViewModels;

namespace RealEstateAgency4.Controllers
{
    [Authorize]
    public class ContractsController : Controller
    {
        private readonly RealEstateAgencyContext _context;

        private readonly int pageSize = 12;

        public ContractsController(RealEstateAgencyContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(SortState sortOrder, int page = 1)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<ContractsCache>();
            ContractsViewModel contractsViewModel;

            var contracts = HttpContext.Session.Get<ContractsViewModel>("Contract");

            if (contracts == null)
            {
                contracts = new ContractsViewModel();
            }

            IEnumerable<Contract> contractContext = cache.GetContracts();

            contractContext = Sort_Search(contractContext, sortOrder, contracts.DateOfContract, contracts.SellerName ?? "", contracts.DealAmount, contracts.ServiceCost,
                contracts.Employee ?? "", contracts.Fiobuyer ?? "");

            var count = contractContext.Count();
            contractContext = contractContext.Skip((page - 1) * pageSize).Take(pageSize);

            ContractsViewModel contractModel = new ContractsViewModel
            {
                contracts = contractContext,
                pageViewModel = new PageViewModel(count, page, pageSize),
                sortViewModel = new SortViewModel(sortOrder),
                DateOfContract = contracts.DateOfContract,
                SellerName = contracts.SellerName,
                DealAmount = contracts.DealAmount,
                ServiceCost = contracts.ServiceCost,
                Employee = contracts.Employee,
                Fiobuyer = contracts.Fiobuyer
            };
            return View(contractModel);

        }

        [HttpPost]
        public async Task<IActionResult> Index(ContractsViewModel contract)
        {
            HttpContext.Session.Set("Contract", contract);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<ContractsCache>();

            if (id == null || _context.Contracts == null)
            {
                return NotFound();
            }

            var contract =  cache.GetContracts()
                .FirstOrDefault(m => m.Id == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        public async Task<IActionResult> Details(int? id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<ContractsCache>();

            if (id == null || _context.Contracts == null)
            {
                return NotFound();
            }

            var contract = cache.GetContracts()
                .FirstOrDefault(m => m.Id == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        public IActionResult Create()
        {
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "FullName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(Contract contract)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<ContractsCache>();

            if (ModelState.IsValid)
            {
                _context.Add(contract);
                await _context.SaveChangesAsync();
                cache.SetContracts();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "FullName", contract.Id);
            return View(contract);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<ContractsCache>();

            if (id == null || _context.Contracts == null)
            {
                return NotFound();
            }

            var contract = cache.GetContracts().FirstOrDefault(m => m.Id == id);
            if (contract == null)
            {
                return NotFound();
            }
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "FullName", contract.Id);
            return View(contract);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, Contract contract)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<ContractsCache>();

            if (id != contract.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contract);
                    await _context.SaveChangesAsync();
                    cache.SetContracts();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractExists(contract.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "FullName", contract.SellerId);
            return View(contract);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cache = HttpContext.RequestServices.GetRequiredService<ContractsCache>();

            if (_context.Contracts == null)
            {
                return Problem("Entity set 'RealEstateAgencyContext.Contracts'  is null.");
            }
            var contract = cache.GetContracts().FirstOrDefault(m => m.Id == id);

            if (contract != null)
            {
                _context.Contracts.Remove(contract);
            }

            await _context.SaveChangesAsync();
            cache.SetContracts();
            return RedirectToAction(nameof(Index));
        }

        private bool ContractExists(int id)
        {
            return (_context.Contracts?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private IEnumerable<Contract> Sort_Search(IEnumerable<Contract> contracts, SortState sortOrder, DateTime? searchDate, string searchSellerName,
            decimal searchDealAmount, decimal searchServiceCost, string searchEmployee, string searchFiobuyer)
        {
            switch (sortOrder)
            {
                case SortState.DateOfContractAsc:
                    contracts = contracts.OrderBy(s => s.DateOfContract);
                    break;
                case SortState.DateOfContractDesc:
                    contracts = contracts.OrderByDescending(s => s.DateOfContract);
                    break;
                case SortState.DealAmountAsc:
                    contracts = contracts.OrderBy(s => s.DealAmount);
                    break;
                case SortState.DealAmountDesc:
                    contracts = contracts.OrderByDescending(s => s.DealAmount);
                    break;
                case SortState.ServiceCostAsc:
                    contracts = contracts.OrderBy(s => s.ServiceCost);
                    break;
                case SortState.ServiceCostDesc:
                    contracts = contracts.OrderByDescending(s => s.ServiceCost);
                    break;


            }
            contracts = contracts
                .Where(c => (c.DateOfContract == searchDate || searchDate == new DateTime() || searchDate == null)
                && (c.Seller.FullName.Contains(searchSellerName ?? ""))
                && (c.DealAmount == searchDealAmount || searchDealAmount == 0)
                && (c.ServiceCost == searchServiceCost || searchServiceCost == 0)
                && (c.Employee == searchEmployee || searchEmployee.IsNullOrEmpty())
                && (c.Fiobuyer == searchFiobuyer || searchFiobuyer.IsNullOrEmpty()));



            return contracts;
        }
    }
}

RealEstateAgency4/Views/Contracts/Create.cshtml
@model RealEstateAgency4.Models.Contract

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавление</h1>

<h4>Договор</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateOfContract" class="control-label"></label>
                <input asp-for="DateOfContract" class="form-control" />
                <span asp-validation-for="DateOfContract" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SellerId" class="control-label"></label>
                <select asp-for="SellerId" class ="form-control" asp-items="ViewBag.SellerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DealAmount" class="control-label"></label>
                <input asp-for="DealAmount" step="any" class="form-control" />
                <span asp-validation-for="DealAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceCost" class="control-label"></label>
                <input asp-for="ServiceCost" step="any" class="form-control" />
                <span asp-validation-for="ServiceCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee" class="control-label"></label>
                <input asp-for="Employee" class="form-control" />
                <span asp-validation-for="Employee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fiobuyer" class="control-label"></label>
                <input asp-for="Fiobuyer" class="form-control" />
                <span asp-validation-for="Fiobuyer" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy2-fill" viewBox="0 0 16 16">
                        <path d="M12 2h-2v3h2z" />
                        <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v13A1.5 1.5 0 0 0 1.5 16h13a1.5 1.5 0 0 0 1.5-1.5V2.914a1.5 1.5 0 0 0-.44-1.06L14.147.439A1.5 1.5 0 0 0 13.086 0zM4 6a1 1 0 0 1-1-1V1h10v4a1 1 0 0 1-1 1zM3 9h10a1 1 0 0 1 1 1v5H2v-5a1 1 0 0 1 1-1" />
                    </svg>
                </button>
            </div>
        </form>
    </div>
</div>
<p></p>
<div>
    <a asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-skip-backward-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
            <path d="M11.729 5.055a.5.5 0 0 0-.52.038L8.5 7.028V5.5a.5.5 0 0 0-.79-.407L5 7.028V5.5a.5.5 0 0 0-1 0v5a.5.5 0 0 0 1 0V8.972l2.71 1.935a.5.5 0 0 0 .79-.407V8.972l2.71 1.935A.5.5 0 0 0 12 10.5v-5a.5.5 0 0 0-.271-.445" />
        </svg>
    </a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        // переопределение валидации на стороне клиента
        $.validator.methods.range = function (value, element, param) {
            var globalizedValue = value.replace(",", ".");
            return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }
        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }
    </script>
}

RealEstateAgency4/Views/Contracts/Index.cshtml
@model ContractsViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    DateTime? DateOfContract = Model.DateOfContract;
    Decimal DealAmount = Model.DealAmount;
    Decimal ServiceCost = Model.ServiceCost;
    string Employee = Model.Employee;
    string Fiobuyer = Model.Fiobuyer;
    string SellerName = Model.SellerName;
}

<h1>Договора</h1>
<p></p>
<div class="d-flex justify-content-between align-items-center">
    @if (User.IsInRole("admin"))
    {
        <p>
            <a asp-action="Create">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" />
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
                </svg>
            </a>
        </p>
    }
    <div class="form-group">
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-funnel" viewBox="0 0 16 16">
                <path d="M1.5 1.5A.5.5 0 0 1 2 1h12a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.128.334L10 8.692V13.5a.5.5 0 0 1-.342.474l-3 1A.5.5 0 0 1 6 14.5V8.692L1.628 3.834A.5.5 0 0 1 1.5 3.5zm1 .5v1.308l4.372 4.858A.5.5 0 0 1 7 8.5v5.306l2-.666V8.5a.5.5 0 0 1 .128-.334L13.5 3.308V2z" />
            </svg>
        </button>
    </div>
</div>
<div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Фильтры</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="container mt-4">
        <form class="form-inline" action="@Url.Action("Index", "Contracts")" method="post">

            <div class="form-group mr-2">
                <label for="DateOfContract">Дата:</label>
                <input asp-for="@Model.DateOfContract" name="DateOfContract" type="date" class="form-control" style="width: 120px;">
            </div>

            <div class="form-group mr-2">
                <label for="DealAmount">Цена сделки:</label>
                @Html.TextBox("DealAmount", DealAmount, new { @class = "form-control", style = "width: 120px;" })
            </div>

            <div class="form-group mr-2">
                <label for="ServiceCost">Стоимость услуги:</label>
                @Html.TextBox("ServiceCost", ServiceCost, new { @class = "form-control", style = "width: 120px;" })
            </div>

            <div class="form-group mr-2">
                <label for="Employee">Сотрудник:</label>
                @Html.TextBox("Employee", Employee, new { @class = "form-control", style = "width: 200px;" })
            </div>

            <div class="form-group mr-2">
                <label for="Fiobuyer">Покупатель:</label>
                @Html.TextBox("Fiobuyer", Fiobuyer, new { @class = "form-control", style = "width: 200px;" })
            </div>

            <div class="form-group mr-2">
                <label for="SellerName">Продавец:</label>
                @Html.TextBox("SellerName", SellerName, new { @class = "form-control", style = "width: 200px;" })
            </div>

            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fiobuyer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SellerName)
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder=@Model.sortViewModel.DateOfContractSort>
                    @Html.DisplayNameFor(model => model.DateOfContract)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder=@Model.sortViewModel.DealAmountSort>
                    @Html.DisplayNameFor(model => model.DealAmount)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder=@Model.sortViewModel.ServiceCostSort>
                    @Html.DisplayNameFor(model => model.ServiceCost)
                </a>            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.contracts) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fiobuyer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seller.FullName)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfContract)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.DealAmount) ₽
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.ServiceCost) ₽
            </td>
            
                @if (User.IsInRole("admin"))
                {
                    <td>
                        <div class="col-md-12 d-flex">
                            <a asp-action="Edit" asp-route-id="@item.Id">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                </svg>
                            </a>
                            <a asp-action="Details" asp-route-id="@item.Id">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2" />
                                </svg>
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.Id">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                                </svg>
                            </a>
                        </div>
                    </td>
                }
                else
                {
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2" />
                            </svg>
                        </a>
                    </td>
                }
            </tr>
}
    </tbody>
</table>

@{
    var totalPages = Model.pageViewModel.TotalPages;
    var currentPage = Model.pageViewModel.PageNumber;
}

<div>
    <ul class="pagination pagination-sm">
        @if (currentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new { page = currentPage - 1 })">&laquo;</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <span class="page-link">&laquo;</span>
            </li>
        }

        @for (int i = Math.Max(1, currentPage - 1); i <= Math.Min(totalPages, currentPage + 1); i++)
        {
            <li class="page-item @(i == currentPage ? "active" : "")">
                <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
            </li>
        }

        @if (currentPage < totalPages)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new { page = currentPage + 1 })">&raquo;</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <span class="page-link">&raquo;</span>
            </li>
        }
    </ul>
</div>